spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/BoardCalendar
    username: postgres
    password: gusdn0110


  thymeleaf:
    prefix: classpath:/templates/template/
    suffix: .html


mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.v1.mapper


logging:
  file:
    path: /log/board

server:
  port: 8080

